CREATE TABLE `RequestCategory`(
	`Category` VARCHAR(40),
	`CategoryID` BIGINT NOT NULL AUTO_INCREMENT,
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`Description` VARCHAR(100),
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`SoftDeleteFlag` BOOLEAN,
	PRIMARY KEY(`CategoryID`)
);
ALTER TABLE `RequestCategory`
	ADD CONSTRAINT `69f6dc76f2eb1f3cebe79c30f289ed` UNIQUE KEY(`Category`),
	ADD CONSTRAINT `b9da6781268af9411ce8a0cefbc1ac` UNIQUE KEY(`CategoryID`);
CREATE TABLE `Request`(
	`AssignedTo` VARCHAR(40),
	`CategoryID` BIGINT,
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`Description` VARCHAR(100),
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`Location` VARCHAR(40),
	`Name` VARCHAR(40),
	`Phone` VARCHAR(40),
	`Photo` VARCHAR(40),
	`RequestID` BIGINT NOT NULL AUTO_INCREMENT,
	`SoftDeleteFlag` BOOLEAN,
	`Status` VARCHAR(100),
	PRIMARY KEY(`RequestID`)
);
ALTER TABLE `Request`
	ADD CONSTRAINT `8e5e22eb20e31c48b80ee620762c7c` UNIQUE KEY(`RequestID`);
ALTER TABLE `Request`
	ADD CONSTRAINT `7a49c84d269875b3246ca834c4c96b` FOREIGN KEY(`CategoryID`) REFERENCES `RequestCategory`(`CategoryID`);
